### ISSUE TITLE
🐛 옵션 상품 테이블 생성

### ISSUE THREAD

**Issue by puclpu** [puclpu/commerce#19]
#### Description
옵션 상품 테이블 생성
- 옵션 마다 재고가 다름

#### Todo
- [x] 상품 테이블에서 재고 컬럼 삭제
- [x] 옵션 상품 테이블 생성
- [x] 위시 테이블에서 상품 옵션 참조 삭제 및 옵션 상품 테이블 참조
- [x] 관련 api 수정

#### ETC
